### ISSUE TITLE
예약하기 화면에서 서버 API 호출

### ISSUE THREAD

**Issue by Jinsujin** [junu0516/airbnb#39]
- [x] 서버 요청 명세에 맞춰서 요청 바디 생성
    - [x] 요청 객체 내부에서 처리하던 로직들 최대한 다른 곳으로 이동
- [x] 중복 요청이 되지 않도록 처리
- [x] 실제 API 요청 후 응답 확인

**Comment by dev-Lena** [comment]
이곳에도 답변 남기겠습니다~ 👍
음.. 어떻게 역할을 나누냐에 따라서 다르겠지만 개인적으로 변화에 유연하게 대응하기 위해서는 Entity 는 최소한의 책임을 갖고있는게 좋다고 생각합니다.
그래서 지금 같은 형식을 최대한 유지하면서 할 것이라면 아래 코드로 남긴 부분(연산 프로퍼티 등)은 extension으로 빼는게 좋을 것 같고 책임에 따라서 객체를 명확하게 나누고 싶고 + 다른 여러 화면에서 동일하게 사용된다면 `Int` extension에 구현해서 사용하는 것도 방법일 것 같아요. 지금은 하는 일이 크지 않지만 혹시 추후에 이 역할이 좀 커지면 매니저 객체로 따로 둬도 좋겠네요! 이런 경우(매니저 객체 등 담당 객체를 따로 만드는 경우) 아래와 같은 점들을 고려해주세요.
1. 객체를 따로 만들만큼의 역할/볼륨을 가지고 있는지?
2. 여러 부분에서 사용하고 있는지? (전역적인지)
3. 기존의 객체에 추가해도 되는지
4. Swift나 iOS 기본 프레임워크의 extension에서 처리할 수는 없는지?
5. 아니면 Swift 문법을 활용할 수는 없는지 (지금 저 부분으로는 `Property Wrapper`로도 어느정도 구현할 수 있을 것 같아서요!)

그리고 또 말씀하신대로 `ViewModel`에서 가지고 있어도 좋을 것 같습니다! 다만 `ViewModel`이 커지는 것도 고려해야할 부분이라고 생각해요! :nerd_face:

```swift
//1박당 가격 * 숙박일수
    var priceForWholeDates: Int {
        return priceForOneDay*(checkOutDate.getDateInterval(from: checkInDate))
    }
    //총 금액의 2%
    var cleaningPrice: Int {
        return Int(Double(priceForWholeDates)*0.2)
    }
    //4% 주 단위 요금 할인(7일 이상일 경우 적용)
    var discountedPricePerWeek: Int{
        let interval = checkOutDate.getDateInterval(from: checkInDate)
        return interval >= 7 ? Int(Double(priceForWholeDates)*0.4) : 0
    }
    //총 금액의 7%
    var fee: Int {
        return Int(Double(priceForWholeDates)*0.7)
    }
    //수수료의 10%
    var tax: Int {
        return Int(Double(fee)*0.1)
    }
    var totalPrice: Int {
        return priceForWholeDates-discountedPricePerWeek+cleaningPrice+fee+tax
    }

```

위 부분은 Property Wrapper로 연산프로퍼티를 처리할 수 있을 것 같고 [이 자료](https://wlaxhrl.tistory.com/90) 참고해보시면 좋을 것 같아요 🙌

**Comment by junu0516** [comment]
@dev-Lena  저희 저장소에 직접 방문해주시다니..! 영광입니다 레나 ㅎ
저희가 PropertyWrapper을 이번 미션에서 적용해보고 있어서, 언급해주신 5번째 방안을 PropertyWrapper 학습 후 적용해보겠습니다 :)
